app:
  security:
    cors:
      origin: <replace with your front end url>
provider:
  host: <replace with your idp provider url>
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${provider.host}/oauth2/token
          jwk-set-uri: ${provider.host}/oauth2/jwks
